# Generated by Django 3.0.8 on 2020-07-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_auto_20200729_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygifts',
            name='user_image',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
