# Generated by Django 3.0.8 on 2020-08-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_auto_20200801_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygifts',
            name='city',
            field=models.CharField(blank=True, choices=[('Safi', 'Safi'), ('Agadir', 'Agadir')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='mygifts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
