# Generated by Django 3.0.8 on 2020-08-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0008_auto_20200804_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandesgift',
            name='gift_owner',
            field=models.CharField(default='', max_length=250),
        ),
    ]
