# Generated by Django 3.0.8 on 2020-08-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0009_demandesgift_gift_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandesgift',
            options={'ordering': ['gift']},
        ),
        migrations.AlterField(
            model_name='demandesgift',
            name='gift',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='demandesgift',
            name='user',
            field=models.CharField(default='', max_length=250),
        ),
    ]
