# Generated by Django 3.0.8 on 2020-08-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0010_auto_20200805_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemandesGift',
        ),
    ]
