# Generated by Django 3.0.8 on 2020-08-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0011_delete_demandesgift'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=250)),
                ('user_city', models.CharField(blank=True, choices=[('Safi', 'Safi'), ('Rabat', 'Rabat'), ('Agadir', 'Agadir'), ('Casablanca', 'Casablanca'), ('Marrakec', 'Marrakech'), ('Beni mellal', 'Beni mellal'), ('Oujda', 'Oujda'), ('Asilah', 'Asilah'), ('Tanger', 'Tanger'), ('Layoune', 'Layoune')], default='', max_length=55)),
                ('user_message', models.TextField(default='', max_length=1000)),
                ('user_email', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('user_phone', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
    ]
