# Generated by Django 3.0.8 on 2020-08-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0012_giftrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftrequest',
            name='user_city',
            field=models.CharField(blank=True, choices=[('Safi', 'Safi'), ('Rabat', 'Rabat'), ('Agadir', 'Agadir'), ('Casablanca', 'Casablanca'), ('Marrakec', 'Marrakech'), ('Beni mellal', 'Beni mellal'), ('Oujda', 'Oujda'), ('Asilah', 'Asilah'), ('Tanger', 'Tanger'), ('Layoune', 'Layoune')], default='', max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='giftrequest',
            name='user_message',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='giftrequest',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
