# Generated by Django 3.0.8 on 2020-08-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0014_auto_20200805_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftrequest',
            options={'ordering': ['gift']},
        ),
        migrations.AddField(
            model_name='giftrequest',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='giftrequest',
            name='stats',
            field=models.CharField(blank=True, default='waiting', max_length=10),
        ),
    ]
