# Generated by Django 3.0.8 on 2020-08-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0016_auto_20200806_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftStatistiques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, max_length=20, null=True)),
                ('total', models.IntegerField(default=0, max_length=20, null=True)),
                ('pending', models.IntegerField(default=0, max_length=20, null=True)),
                ('accepted', models.IntegerField(default=0, max_length=20, null=True)),
                ('rejected', models.IntegerField(default=0, max_length=20, null=True)),
            ],
        ),
    ]
