# Generated by Django 3.0.8 on 2020-08-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0017_giftstatistiques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftstatistiques',
            name='accepted',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='giftstatistiques',
            name='pending',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='giftstatistiques',
            name='rejected',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='giftstatistiques',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='giftstatistiques',
            name='user',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
