# Generated by Django 3.0.8 on 2020-08-06 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0018_auto_20200806_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftrequest',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.Mygifts'),
        ),
    ]
