# Generated by Django 3.0.8 on 2020-08-07 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0019_auto_20200806_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mygifts',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='mygifts',
            name='user_id',
        ),
        migrations.AddField(
            model_name='mygifts',
            name='gived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
