# Generated by Django 3.0.8 on 2020-08-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0020_auto_20200807_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygifts',
            name='image_url',
        ),
    ]
