# Generated by Django 3.0.8 on 2020-08-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0022_auto_20200807_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftStatistiques',
        ),
    ]
