# Generated by Django 3.0.8 on 2020-08-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0025_auto_20200808_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_read',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
