# Generated by Django 3.0.8 on 2020-08-09 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0026_auto_20200808_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date_start', models.DateTimeField(auto_now=True)),
                ('date_close', models.DateTimeField(blank=True, default=None, null=True)),
                ('c_guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_guest', to=settings.AUTH_USER_MODEL)),
                ('c_host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_host', to=settings.AUTH_USER_MODEL)),
                ('gift', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gifts.Mygifts')),
            ],
            options={
                'ordering': ['-date_start'],
            },
        ),
    ]
