# Generated by Django 3.0.8 on 2020-08-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0027_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='guest_avatar',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='host_avatar',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
