# Generated by Django 3.0.8 on 2020-08-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0028_auto_20200810_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='conversation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gifts.Conversation'),
        ),
    ]
