# Generated by Django 3.0.8 on 2020-08-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0029_auto_20200810_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='gift',
        ),
    ]
