# Generated by Django 3.0.8 on 2020-08-10 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0034_auto_20200810_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='gift',
        ),
        migrations.AddField(
            model_name='messages',
            name='conversation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gifts.Conversation'),
        ),
        migrations.AlterField(
            model_name='giftrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
