# Generated by Django 3.0.8 on 2020-08-10 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0035_auto_20200810_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, choices=[('Safi', 'Safi'), ('Rabat', 'Rabat'), ('Agadir', 'Agadir'), ('Casablanca', 'Casablanca'), ('Marrakec', 'Marrakech'), ('Beni mellal', 'Beni mellal'), ('Oujda', 'Oujda'), ('Asilah', 'Asilah'), ('Tanger', 'Tanger'), ('Layoune', 'Layoune')], default='', max_length=55)),
                ('user_image', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
