# Generated by Django 3.0.8 on 2020-08-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0036_auto_20200810_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['date_send']},
        )
    ]
