# Generated by Django 3.0.8 on 2020-08-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0037_auto_20200810_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='guest_avatar',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='host_avatar',
        ),
    ]
