# Generated by Django 3.0.8 on 2020-08-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0038_auto_20200811_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='viewd',
            new_name='seen_by_receiver',
        ),
        migrations.AddField(
            model_name='messages',
            name='seen_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
