# Generated by Django 3.0.8 on 2020-08-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0039_auto_20200812_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='seen_by_receiver',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='seen_by_sender',
        ),
        migrations.AddField(
            model_name='messages',
            name='is_seen',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
