# Generated by Django 3.0.8 on 2020-08-24 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0041_conversation_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftrequest',
            name='user_city',
            field=models.CharField(blank=True, choices=[('Safi', 'Safi'), ('Essaouira', 'Essaouira'), ('Rabat', 'Rabat'), ('Agadir', 'Agadir'), ('Casablanca', 'Casablanca'), ('Marrakech', 'Marrakech'), ('Beni mellal', 'Beni mellal'), ('Oujda', 'Oujda'), ('Asilah', 'Asilah'), ('Tanger', 'Tanger'), ('Layoune', 'Layoune')], default='', max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='mygifts',
            name='city',
            field=models.CharField(blank=True, choices=[('Safi', 'Safi'), ('Essaouira', 'Essaouira'), ('Rabat', 'Rabat'), ('Agadir', 'Agadir'), ('Casablanca', 'Casablanca'), ('Marrakech', 'Marrakech'), ('Beni mellal', 'Beni mellal'), ('Oujda', 'Oujda'), ('Asilah', 'Asilah'), ('Tanger', 'Tanger'), ('Layoune', 'Layoune')], default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, choices=[('Safi', 'Safi'), ('Essaouira', 'Essaouira'), ('Rabat', 'Rabat'), ('Agadir', 'Agadir'), ('Casablanca', 'Casablanca'), ('Marrakech', 'Marrakech'), ('Beni mellal', 'Beni mellal'), ('Oujda', 'Oujda'), ('Asilah', 'Asilah'), ('Tanger', 'Tanger'), ('Layoune', 'Layoune')], default='', max_length=55),
        ),
        migrations.CreateModel(
            name='Notifictaion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='notice', max_length=55)),
                ('level', models.CharField(blank=True, default='info', max_length=55)),
                ('verb', models.TextField(max_length=500)),
                ('unread', models.BooleanField(default=True)),
                ('absolute_url', models.CharField(blank=True, max_length=250, null=True)),
                ('date_send', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gifts.Mygifts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
