# Generated by Django 3.0.8 on 2020-08-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0042_auto_20200824_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=55),
        ),
    ]
