# Generated by Django 3.0.8 on 2020-08-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0043_auto_20200824_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifictaion',
            name='target',
            field=models.IntegerField(blank=True, max_length=55, null=True),
        ),
    ]
